"""Investigation workflow for OpsPilot AI.

This workflow selects mock Kubernetes tools, gathers evidence, aggregates the
results into a structured JSON object, and then passes that context into the
existing OpenAI Responses API path through the established service layer.
"""

from __future__ import annotations

import json
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field

from app.agents.prompt_builder import PromptBuilder, PromptBundle
from app.core.exceptions import OpsPilotError
from app.core.logging import get_logger
from app.remediation.engine import RemediationEngine
from app.schemas.investigation import InvestigationRequest, InvestigationResponse
from app.reports.generator import ReportGenerator
from app.services.openai_service import OpenAIService
from app.tools.registry import ToolRegistry

logger = get_logger(__name__)


class InvestigationWorkflowError(OpsPilotError):
    """Base error for investigation workflow failures."""


class ToolPlan(BaseModel):
    """Declarative description of a tool invocation in the workflow."""

    tool_name: str = Field(description="Registered tool name.")
    operation: str = Field(description="Tool operation to execute.")
    evidence_key: str = Field(description="Key under which tool output is stored.")
    kwargs: dict[str, Any] = Field(default_factory=dict, description="Tool execution kwargs.")

    model_config = ConfigDict(extra="forbid")


class ToolResult(BaseModel):
    """Serializable result record for one tool execution attempt."""

    tool_name: str
    operation: str
    evidence_key: str
    status: Literal["success", "failed", "unavailable"]
    output: Any | None = None
    error: str | None = None

    model_config = ConfigDict(extra="forbid")


class InvestigationEvidence(BaseModel):
    """Aggregated evidence generated by the workflow."""

    incident: str
    tool_results: dict[str, Any]
    selected_tools: list[str]
    failures: list[ToolResult] = Field(default_factory=list)

    model_config = ConfigDict(extra="forbid")


class InvestigationWorkflow:
    """Gather evidence and coordinate prompt creation for investigations."""

    def __init__(
        self,
        *,
        tool_registry: ToolRegistry,
        prompt_builder: PromptBuilder | None = None,
        remediation_engine: RemediationEngine | None = None,
        report_generator: ReportGenerator | None = None,
    ) -> None:
        self.tool_registry = tool_registry
        self.prompt_builder = prompt_builder or PromptBuilder()
        self.remediation_engine = remediation_engine or RemediationEngine()
        self.report_generator = report_generator or ReportGenerator()

    def run(self, request: InvestigationRequest, openai_service: OpenAIService) -> InvestigationResponse:
        incident = request.incident.strip()
        if not incident:
            raise InvestigationWorkflowError(
                "Incident must not be empty.",
                status_code=422,
            )

        logger.info(
            "investigation_workflow_started",
            extra={"incident": incident},
        )

        selected_plans = self._select_tool_plans(incident)
        logger.info(
            "investigation_workflow_selected_tools",
            extra={
                "incident": incident,
                "tools": [plan.tool_name for plan in selected_plans],
            },
        )

        evidence = self._gather_evidence(incident, selected_plans)
        evidence_payload = evidence.model_dump(mode="json")

        logger.info(
            "investigation_workflow_evidence_aggregated",
            extra={
                "incident": incident,
                "selected_tools": evidence.selected_tools,
                "failure_count": len(evidence.failures),
            },
        )

        prompt_bundle = self._build_prompts(incident, evidence_payload)
        logger.info(
            "investigation_workflow_prompt_generated",
            extra={
                "incident": incident,
                "prompt_length": len(prompt_bundle.user_prompt),
            },
        )

        logger.info(
            "investigation_workflow_openai_call",
            extra={
                "incident": incident,
                "selected_tools": evidence.selected_tools,
            },
        )
        response = openai_service.generate_investigation_response(
            incident=incident,
            system_prompt=prompt_bundle.system_prompt,
            user_prompt=prompt_bundle.user_prompt,
        )

        remediation_actions = self.remediation_engine.generate(
            investigation=response,
            evidence=evidence_payload,
        )
        response.remediation = self.remediation_engine.render_summary(remediation_actions)

        logger.info(
            "investigation_workflow_remediation_generated",
            extra={
                "incident": incident,
                "recommendation_count": len(remediation_actions),
                "categories": [action.category for action in remediation_actions],
                "status": [action.status.value for action in remediation_actions],
            },
        )

        report = self.report_generator.generate(
            incident=incident,
            investigation=response,
            evidence=evidence_payload,
            remediation_actions=remediation_actions,
            metadata={
                "openai_model": getattr(openai_service, "model", None),
                "workflow_version": "m8",
                "selected_tools": evidence.selected_tools,
                "failure_count": len(evidence.failures),
                "tool_result_keys": list(evidence.tool_results.keys()),
            },
        )

        logger.info(
            "investigation_workflow_report_generated",
            extra={
                "incident": incident,
                "report_id": str(report.report_id),
                "section_count": len(report.investigation_timeline),
            },
        )

        logger.info(
            "investigation_workflow_completed",
            extra={
                "incident": incident,
                "confidence": response.confidence,
            },
        )
        return response

    def _build_prompts(self, incident: str, evidence: dict[str, Any]) -> PromptBundle:
        try:
            return self.prompt_builder.build(
                incident=incident,
                evidence=evidence,
            )
        except Exception as exc:  # noqa: BLE001
            logger.exception(
                "investigation_workflow_prompt_build_failed",
                extra={"incident": incident, "error_type": exc.__class__.__name__},
            )
            raise InvestigationWorkflowError(
                "Failed to build investigation prompts.",
                status_code=500,
            ) from exc

    def _gather_evidence(self, incident: str, plans: list[ToolPlan]) -> InvestigationEvidence:
        tool_results: dict[str, Any] = {}
        failures: list[ToolResult] = []
        selected_tools: list[str] = []

        for plan in plans:
            selected_tools.append(plan.tool_name)
            logger.info(
                "investigation_workflow_tool_execution_started",
                extra={
                    "incident": incident,
                    "tool_name": plan.tool_name,
                    "operation": plan.operation,
                    "evidence_key": plan.evidence_key,
                },
            )

            try:
                tool = self.tool_registry.get(plan.tool_name)
            except KeyError as exc:
                failure = ToolResult(
                    tool_name=plan.tool_name,
                    operation=plan.operation,
                    evidence_key=plan.evidence_key,
                    status="unavailable",
                    error=str(exc),
                )
                failures.append(failure)
                tool_results[plan.evidence_key] = failure.model_dump(mode="json")
                logger.info(
                    "investigation_workflow_tool_unavailable",
                    extra={
                        "incident": incident,
                        "tool_name": plan.tool_name,
                        "operation": plan.operation,
                    },
                )
                continue

            try:
                output = tool.execute(operation=plan.operation, **plan.kwargs)
                self._assert_json_serializable(output)
                result = ToolResult(
                    tool_name=plan.tool_name,
                    operation=plan.operation,
                    evidence_key=plan.evidence_key,
                    status="success",
                    output=output,
                )
                tool_results[plan.evidence_key] = result.model_dump(mode="json")
                logger.info(
                    "investigation_workflow_tool_execution_completed",
                    extra={
                        "incident": incident,
                        "tool_name": plan.tool_name,
                        "operation": plan.operation,
                        "evidence_key": plan.evidence_key,
                    },
                )
            except Exception as exc:  # noqa: BLE001
                failure = ToolResult(
                    tool_name=plan.tool_name,
                    operation=plan.operation,
                    evidence_key=plan.evidence_key,
                    status="failed",
                    error=str(exc),
                )
                failures.append(failure)
                tool_results[plan.evidence_key] = failure.model_dump(mode="json")
                logger.exception(
                    "investigation_workflow_tool_execution_failed",
                    extra={
                        "incident": incident,
                        "tool_name": plan.tool_name,
                        "operation": plan.operation,
                        "evidence_key": plan.evidence_key,
                        "error_type": exc.__class__.__name__,
                    },
                )

                continue

            if plan.tool_name == "kubernetes.pod" and plan.operation == "get_pods":
                pod_name = self._select_pod_name(incident, output)
                if pod_name:
                    self._append_pod_detail(incident, pod_name, tool_results, failures)

        return InvestigationEvidence(
            incident=incident,
            tool_results=tool_results,
            selected_tools=selected_tools,
            failures=failures,
        )

    def _select_tool_plans(self, incident: str) -> list[ToolPlan]:
        lowered = incident.lower()
        plans: list[ToolPlan] = []

        if "crashloopbackoff" in lowered:
            plans.extend(self._pod_plans())
            plans.append(self._event_plan())
        elif "imagepullbackoff" in lowered:
            plans.extend(self._pod_plans())
            plans.append(self._event_plan())
        elif "pending" in lowered:
            plans.extend(self._pod_plans())
            plans.append(self._node_plan())
        elif "oomkilled" in lowered:
            plans.extend(self._pod_plans())
        elif "nodenotready" in lowered or "node not ready" in lowered:
            plans.append(self._node_plan())
            plans.extend(self._pod_plans())
        elif "service unavailable" in lowered:
            plans.append(self._service_plan())
            plans.extend(self._pod_plans())
        elif "deployment failure" in lowered:
            plans.append(self._deployment_plan())
            plans.extend(self._pod_plans())
        else:
            plans.extend(self._pod_plans())

        return self._dedupe_plans(plans)

    def _pod_plans(self) -> list[ToolPlan]:
        plans = [ToolPlan(tool_name="kubernetes.pod", operation="get_pods", evidence_key="pods")]
        return plans

    @staticmethod
    def _event_plan() -> ToolPlan:
        return ToolPlan(tool_name="kubernetes.event", operation="get_events", evidence_key="events")

    @staticmethod
    def _node_plan() -> ToolPlan:
        return ToolPlan(tool_name="kubernetes.node", operation="get_nodes", evidence_key="nodes")

    @staticmethod
    def _service_plan() -> ToolPlan:
        return ToolPlan(tool_name="kubernetes.service", operation="get_services", evidence_key="services")

    @staticmethod
    def _deployment_plan() -> ToolPlan:
        return ToolPlan(tool_name="kubernetes.deployment", operation="get_deployments", evidence_key="deployments")

    @staticmethod
    def _dedupe_plans(plans: list[ToolPlan]) -> list[ToolPlan]:
        seen: set[tuple[str, str, str]] = set()
        deduped: list[ToolPlan] = []
        for plan in plans:
            identity = (plan.tool_name, plan.operation, plan.evidence_key)
            if identity in seen:
                continue
            seen.add(identity)
            deduped.append(plan)
        return deduped

    @staticmethod
    def _assert_json_serializable(value: Any) -> None:
        try:
            json.dumps(value)
        except TypeError as exc:
            raise InvestigationWorkflowError(
                "Tool output must be JSON serializable.",
                status_code=502,
            ) from exc

    def _append_pod_detail(
        self,
        incident: str,
        pod_name: str,
        tool_results: dict[str, Any],
        failures: list[ToolResult],
    ) -> None:
        logger.info(
            "investigation_workflow_tool_execution_started",
            extra={
                "incident": incident,
                "tool_name": "kubernetes.pod",
                "operation": "describe_pod",
                "pod_name": pod_name,
                "evidence_key": "pod_detail",
            },
        )

        try:
            tool = self.tool_registry.get("kubernetes.pod")
            output = tool.execute(operation="describe_pod", name=pod_name)
            self._assert_json_serializable(output)
            result = ToolResult(
                tool_name="kubernetes.pod",
                operation="describe_pod",
                evidence_key="pod_detail",
                status="success",
                output=output,
            )
            tool_results["pod_detail"] = result.model_dump(mode="json")
            logger.info(
                "investigation_workflow_tool_execution_completed",
                extra={
                    "incident": incident,
                    "tool_name": "kubernetes.pod",
                    "operation": "describe_pod",
                    "pod_name": pod_name,
                    "evidence_key": "pod_detail",
                },
            )
        except Exception as exc:  # noqa: BLE001
            failure = ToolResult(
                tool_name="kubernetes.pod",
                operation="describe_pod",
                evidence_key="pod_detail",
                status="failed",
                error=str(exc),
            )
            failures.append(failure)
            tool_results["pod_detail"] = failure.model_dump(mode="json")
            logger.exception(
                "investigation_workflow_tool_execution_failed",
                extra={
                    "incident": incident,
                    "tool_name": "kubernetes.pod",
                    "operation": "describe_pod",
                    "pod_name": pod_name,
                    "evidence_key": "pod_detail",
                    "error_type": exc.__class__.__name__,
                },
            )

    @staticmethod
    def _select_pod_name(incident: str, pods_payload: dict[str, Any]) -> str | None:
        pods = pods_payload.get("pods", [])
        if not isinstance(pods, list):
            return None

        statuses = [
            "CrashLoopBackOff",
            "ImagePullBackOff",
            "Pending",
            "OOMKilled",
            "Unknown",
            "Running",
            "Completed",
        ]

        for status in statuses:
            if status.lower() in incident.lower():
                for pod in pods:
                    if isinstance(pod, dict) and pod.get("status") == status:
                        name = pod.get("name")
                        if isinstance(name, str) and name:
                            return name

        for pod in pods:
            if isinstance(pod, dict):
                name = pod.get("name")
                if isinstance(name, str) and name:
                    return name

        return None
